<aside class="Hui-aside">

    <div class="menu_dropdown bk_2">
        <ul>
            <!--                    <a title="修改密码" href="javascript:;" onclick="editpassword('修改密码','/user/editpasswordv','1','800','500')" >-->

            <li><a title="修改密码" href="javascript:;" onclick="editpassword('修改密码','/user/editpasswordv','<?=$_SESSION["id"]?>','800','500')" >修改密码</li>
            <li><a href="/apikey/apikeyv" title="apikey管理">apikey管理</a></li>
            <li><a href="/domains/listv" title="产品管理">任务管理</a></li>
            <li><a href="/template/listv" title="模板管理">模板管理</a></li>
        </ul>
    </div>
</aside>